import Link from 'next/link';
import { Shell } from '@/components/site-shell';
import { Reveal } from '@/components/reveal';

const items = [['Snap & extract','Photograph an electricity bill, fuel receipt, or travel ticket. Snap2Green reads the numbers straight off the image &mdash; no typing, no forms, no daily habit to keep up.'],['Fuel, generators & vehicles','Direct combustion &mdash; diesel generators, boilers, your own vehicle &mdash; is read straight from the receipt and mapped to the right fuel-specific factor.'],['Electricity, mapped to your grid','Purchased electricity is matched to the correct regional CEA grid factor &mdash; Western, Southern, or otherwise &mdash; instead of one number applied to the whole country.'],['Hotspot insights','Rather than a single flat total, Snap2Green shows which one source &mdash; the generator, the AC load, the commute &mdash; is actually responsible for most of the number.'],['One recommendation, not a list','Snap2Green turns the biggest hotspot into a single priority action, so what you get back is "change this," not a dashboard you have to interpret yourself.'],['Instant PDF report','A branded, downloadable report generated the moment your number is ready &mdash; the figure, the source factors behind it, and the recommendation, laid out to share.'],['Supplier & travel emissions','Value-chain emissions &mdash; suppliers, business travel, upstream transport &mdash; are real, but deliberately left out for now so the number you get today stays fast and verifiable.']];

function Visual({ index }) { return <div className="fd-visual"><svg viewBox="0 0 200 160" width="200" height="160" fill="none"><circle cx="100" cy="80" r="55" fill="#27272A"/><path d="M100 45c-14 14-22 28-22 40a22 22 0 0044 0c0-12-8-26-22-40z" fill={index === 6 ? '#52525B' : '#16A34A'}/><path d="M100 62c-8 8-13 16-13 23a13 13 0 0026 0c0-7-5-15-13-23z" fill="#4ADE80"/></svg></div>; }

export default function FeaturesPage() { return <Shell current="features"><main><section className="page-hero"><Reveal><div className="wrap"><p className="eyebrow">What you get</p><h1 style={{ marginTop: 10 }}>Everything your number needs, in one app.</h1><p className="lede">Six things Snap2Green does with a single photo, and one thing it deliberately doesn't do yet.</p></div></Reveal></section><section style={{ paddingTop: 0 }}><div className="wrap">{items.map(([title, text], index) => <Reveal key={title} className={`feature-detail ${index % 2 ? 'reverse' : ''}`}><div><span className={`fd-badge ${index === 6 ? 'roadmap' : ''}`}>{index === 6 ? 'On the roadmap' : 'Available now'}</span><h3>{title}</h3><p dangerouslySetInnerHTML={{ __html: text }} /></div><Visual index={index} /></Reveal>)}</div></section><section className="band-moss"><Reveal><div className="wrap cta-final"><div><p className="eyebrow">Ready when you are</p><h2 style={{ marginTop: 10 }}>Try it on your next bill.</h2></div><Link className="btn-primary" href="/contact">Get early access</Link></div></Reveal></section></main></Shell>; }
